const projectsData = [
  {
    id: "handsketches",
    title: "Observational Hand Sketches",
    subtitle: "An exploration of form, light, and classical order.",
    description: `
          <p>This collection is fundamental to my practice. It's an act of analysis—deconstructing classical architecture and everyday scenes into their core components of light, shadow, proportion, and texture.</p>
          <p>For me, drawing is the most direct and intuitive way to understand space and begin the process of creative ideation. Each piece is a study in observation and discipline.</p>
      `,
    tools: ["Pencil & Paper", "Fine-line Pens", "Digital Coloring"],
    images: [
      "images/sketches/sketch_01.jpg",
      "images/sketches/sketch_02.jpg",
      "images/sketches/sketch_03.jpg",
      "images/sketches/sketch_04.jpg",
      "images/sketches/sketch_05.jpg",
      "images/sketches/sketch_06.jpg",
      "images/sketches/sketch_07.jpg",
      "images/sketches/sketch_08.jpg",
      "images/sketches/sketch_09.jpg",
      "images/sketches/sketch_10.jpg",
      "images/sketches/sketch_11.jpg",
      "images/sketches/sketch_12.jpg",
      "images/sketches/sketch_13.jpg",
      "images/sketches/sketch_14.jpg",
      "images/sketches/sketch_15.jpg",
      "images/sketches/sketch_16.jpg",
      "images/sketches/sketch_17.jpg",
      "images/sketches/sketch_18.jpg",
      "images/sketches/sketch_19.jpg",
      "images/sketches/sketch_20.jpg",
      "images/sketches/sketch_21.jpg",
    ],
  },
  {
    id: "school",
    title: "The Agora School",
    subtitle: "A proposal for a collaborative learning hub.",
    description: `
          <p>Moving beyond the traditional model of isolated classrooms, this project proposes a school designed as a vibrant, interconnected community. The design is organized around a central, multi-story atrium—a modern-day "agora"—that serves as the social and academic heart of the building.</p>
          <p>The key design principles were flexibility, connectivity, and access to natural light, realized through parametric design and rendered in Lumion to visualize the final atmosphere.</p>
      `,
    tools: ["Rhino & Grasshopper", "Lumion", "Adobe Photoshop"],
    images: [
      "images/school/school_01.jpg",
      "images/school/school_02.jpg",
      "images/school/school_03.jpg",
      "images/school/school_04.jpg",
      "images/school/school_05.jpg",
      "images/school/school_06.jpg",
      "images/school/school_07.jpg",
      "images/school/school_08.jpg",
      "images/school/school_09.jpg",
      "images/school/school_10.jpg",
      "images/school/school_11.jpg",
      "images/school/school_12.jpg",
      "images/school/school_13.jpg",
      "images/school/school_14.jpg",
      "images/school/school_15.jpg",
      "images/school/school_16.jpg",
      "images/school/school_17.jpg",
      "images/school/school_18.jpg",
      "images/school/school_19.jpg",
      "images/school/school_20.jpg",
      "images/school/school_21.jpg",
      "images/school/school_22.jpg",
      "images/school/school_23.jpg",
      "images/school/school_24.jpg",
      "images/school/school_25.jpg",
      "images/school/school_26.jpg",
      "images/school/school_27.jpg",
      "images/school/school_28.jpg",
      "images/school/school_29.jpg",
      "images/school/school_30.jpg",
      "images/school/school_31.jpg",
      "images/school/school_32.jpg",
      "images/school/school_33.jpg",
      "images/school/school_34.jpg",
      "images/school/school_35.jpg",
      "images/school/school_36.jpg",
      "images/school/school_37.jpg",
      "images/school/school_38.jpg",
    ],
  },
  {
    id: "classics",
    title: "Deconstructing the Classics",
    subtitle: "A 3D analysis of Greek and Roman architectural orders.",
    description: `
          <p>To design the future, we must first understand the principles of the past. This series of studies is a deep dive into the classical orders, analyzing their proportional systems and geometric underpinnings through meticulous 3D modeling in Rhino.</p>
          <p>This was more than a historical exercise; it was a lesson in logic, hierarchy, and the timeless relationship between structural necessity and aesthetic expression.</p>
      `,
    tools: ["Rhino", "Adobe Photoshop", "3D Modeling"],
    images: [
      "images/classics/classic_01.png",
      "images/classics/classic_02.png",
      "images/classics/classic_03.png",
      "images/classics/classic_04.png",
      "images/classics/classic_05.png",
      "images/classics/classic_06.png",
      "images/classics/classic_07.png",
      "images/classics/classic_08.png",
      "images/classics/classic_09.jpg",
      "images/classics/classic_10.png",
    ],
  },
  {
    id: "pavilion",
    title: "The Light Weaver Pavilion",
    subtitle: "A parametric study of structure and atmospheric light.",
    description: `
          <p>This project explores the relationship between a structural system and the atmospheric quality of light. Conceived as a destination for quiet contemplation, the architecture itself becomes an instrument for filtering and modulating daylight.</p>
          <p>The primary design challenge was to create an organic, yet rational, form, achieved through a parametric approach using Grasshopper to generate and optimize the complex rib-like structure.</p>
      `,
    tools: ["Rhino & Grasshopper", "Lumion", "Adobe Photoshop"],
    images: [
      "images/pavilion/pavilion_01.jpg",
      "images/pavilion/pavilion_02.jpg",
      "images/pavilion/pavilion_03.jpg",
      "images/pavilion/pavilion_04.jpg",
      "images/pavilion/pavilion_05.jpg",
      "images/pavilion/pavilion_06.jpg",
      "images/pavilion/pavilion_07.jpg",
      "images/pavilion/pavilion_08.jpg",
      "images/pavilion/pavilion_09.jpg",
      "images/pavilion/pavilion_10.jpg",
      "images/pavilion/pavilion_11.jpg",
      "images/pavilion/pavilion_12.jpg",
      "images/pavilion/pavilion_13.jpg",
      "images/pavilion/pavilion_14.jpg",
      "images/pavilion/pavilion_15.jpg",
      "images/pavilion/pavilion_16.jpg",
      "images/pavilion/pavilion_17.jpg",
      "images/pavilion/pavilion_18.jpg",
      "images/pavilion/pavilion_19.jpg",
    ],
  },
  {
    id: "digital_painting",
    title: "Digital Painting with Clip Studio Paint",
    subtitle: "Studies in color, composition, and digital illustration.",
    description: `
          <p>This collection showcases my explorations into digital painting and illustration using Clip Studio Paint. Each piece is an exercise in composition, color theory, and blending techniques to create atmospheric and narrative-driven scenes.</p>
      `,
    tools: ["Clip Studio Paint", "Digital Illustration"],
    images: [
      "images/digital_painting/digital_01.jpg",
      "images/digital_painting/digital_02.jpg",
      "images/digital_painting/digital_03.jpg",
      "images/digital_painting/digital_04.jpg",
      "images/digital_painting/digital_05.jpg",
      "images/digital_painting/digital_06.jpg",
      "images/digital_painting/digital_07.jpg",
      "images/digital_painting/digital_08.jpg",
      "images/digital_painting/digital_09.jpg",
      "images/digital_painting/digital_10.jpg",
      "images/digital_painting/digital_11.jpg",
      "images/digital_painting/digital_12.jpg",
      "images/digital_painting/digital_13.jpg",
    ],
  },
  {
    id: "procreate",
    title: "Digital Sketching with Procreate",
    subtitle: "Creative explorations and ideation on the iPad.",
    description: `
          <p>Procreate offers a fluid and intuitive canvas for quick ideation and digital sketching. This gallery includes a mix of architectural concepts, character studies, and creative experiments, highlighting the versatility of the tool for visual thinking.</p>
      `,
    tools: ["Procreate", "Adobe Photoshop", "Digital Sketching"],
    images: [
      "images/procreate/procreate_01.jpg",
      "images/procreate/procreate_02.jpg",
      "images/procreate/procreate_03.jpg",
      "images/procreate/procreate_04.jpg",
      "images/procreate/procreate_05.jpg",
      "images/procreate/procreate_06.jpg",
      "images/procreate/procreate_07.jpg",
      "images/procreate/procreate_08.jpg",
    ],
  },
];
